apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: stateful-app
data:
  APP_NAME: "KubeState Recovery Lab API"
  APP_ENV: "dev"
  POSTGRES_HOST: "postgres.stateful-app.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "kubestate"
  POSTGRES_USER: "kubestate"
  REDIS_HOST: "redis.stateful-app.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  APP_STARTUP_SCHEMA_TIMEOUT_SECONDS: "5"
  DB_CONNECT_TIMEOUT_SECONDS: "2"
  DB_POOL_SIZE: "2"
  DB_MAX_OVERFLOW: "0"
  DB_POOL_TIMEOUT_SECONDS: "2"
  REDIS_CONNECT_TIMEOUT_SECONDS: "2"
  REDIS_SOCKET_TIMEOUT_SECONDS: "2"
